production:
  address:        smtp.sendgrid.net
  port:           587
  authentication: plain
  user_name:      <%=ENV['SENDGRID_USERNAME']%>
  password:       <%=ENV['SENDGRID_PASSWORD']%>
  domain:         heroku.com

development:
  delivery_method: file

test:
  delivery_method: test

