# myapp/config/s3.yml

development: &DEFAULTS
  bucket: openkitchen-eu
  path: ":rails_env/:class/:attachment/:id/:basename-:style.:extension"

  storage: s3
  s3_permissions: private  
  s3_protocol: https
  s3_credentials:
    access_key_id: <%= ENV['S3_KEY'] %>
    secret_access_key: <%= ENV['S3_SECRET'] %>

production:
  <<: *DEFAULTS

test:
  <<: *DEFAULTS

staging:
  <<: *DEFAULTS


